# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://production-reviewee-api.herokuapp.com/notification/ci
    - url: https://production-reviewee-api.herokuapp.com/notification/microsoftTeams
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/omni-ui

    environment:
      NODE_ENV: testing

    steps:
      - checkout

      # - run:
      #     name: Check Rejected Commits
      #     command: wget ${REVIEWEE_URL}/${COMMITS_CHECK_ENDPOINT} -q -O - | grep -q ${COMMITS_CHECK_INDICATOR}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test -w 1
